Profile-card-{Harsh Pathak}
DiyaVj/Profile-Card-Collection pull request #159
Opened 2022-10-17 17:22 UTC by pathakharsh123

Profile-card{Harsh Pathak}

2022-10-17 17:41 UTC, DiyaVj requested changes
Hey @pathakharsh123!
Please add your details along with your hosted profile card link in the readme.md file of Profile-Card-Collection folder.

2022-10-17 18:13 UTC, pathakharsh123 commented
updated readme.md file

2022-10-17 18:20 UTC, DiyaVj commented
Your attached website link is not working. Can your check it once again?

2022-10-19 18:15 UTC, DiyaVj approved these changes

2022-10-19 18:17 UTC, merged